### ISSUE TITLE
Problem with custom base URL

### ISSUE THREAD

**Issue by derekcicerone-zz** [federecio/dropwizard-swagger#18]
We have all our Jersey APIs running under /api.  When I add the Swagger module to DropWizard it seems to put /swagger under /api (so /api/swagger) but it still expects /api-docs to be at the root (vs /api/api-docs). I didn't see a good way to fix the "api-docs" URL so that its properly nested under /api.

**Comment by aaaaahaaaaa** [comment]
The problem originally described by @derekcicerone seems to be an existing bug with 0.5.3. Swagger tries to load api-docs from the base url `localhost:8080/api-docs` instead of `localhost:8080/api/api-docs` after setting a custom base url with : 
```java
environment.jersey().setUrlPattern("/api/*");
```

**Comment by yeraabh** [comment]
I think there is still an issue in version 0.5.3 with simple server and a custom url pattern.

In getContextPath() of SwaggerConfiguration, contextPath is read from applicationContextPath()

  if (serverFactory instanceof SimpleServerFactory) {
            applicationContextPath = ((SimpleServerFactory) serverFactory).getApplicationContextPath();
