### ISSUE TITLE
No support for setting api.version?

### ISSUE THREAD

**Issue by marcelstoer** [federecio/dropwizard-swagger#24]
I don't see how I could set the `api.version` parameter for Swagger. It's not documented here and the dropwizard-swagger sample application also doesn't show. The API version is reported as 0.0 there as well.

**Comment by Zapata** [comment]
I'm also interested in this feature.

A setter method is good for me, as version is in the manifest and retrieved using: getClass().getPackage().getImplementationVersion()

**Comment by marcelstoer** [comment]
> version is in the manifest and retrieved using: `getClass().getPackage().getImplementationVersion()`

Please note that API version is not necessarily the same as the implementation version. It might be that your application goes from 1.0 to 1.1 to 1.2 and then to 2.x, 3.x, etc. while the API remains stable at 1.0 or v1 or whatever version you assigned to it.

**Comment by federecio** [comment]
This is now supported in the latest version 0.7.0

Follow the instructions in the readme and make sure your config yaml looks like:

```
swagger:
  resourcePackage: <a comma separated string of the packages that contain your @Api annotated resources>
  version: your_version
```

See [SwaggerBundleConfiguration.java](src/main/java/io/federecio/dropwizard/swagger/SwaggerBundleConfiguration.java) for more configuration options.
