### ISSUE TITLE
Swagger 0.5.2 doesn't support  "application/x-www-form-urlencoded" media type

### ISSUE THREAD

**Issue by fafzal** [federecio/dropwizard-swagger#27]
I am trying out swagger 0.5.2, it doesn't  support "application/x-www-form-urlencoded" media type. It generates a doc successfully but when I send a request, it gives 500 error message.

<< Source Code >>

@POST
	@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
	@ApiOperation(
			  value = "Get access token",
			  notes = "Authenticate user and get a access token.",
			  response = TokenResponse.class
	)
	public TokenResponse postForToken(
			  @FormParam("grant_type") @ApiParam(defaultValue = "password") String grantType,
			  @FormParam("username") @ApiParam(defaultValue = "q") String username,
			  @FormParam("password") @ApiParam(defaultValue = "q") String password,
			  @FormParam("client_id") @ApiParam(defaultValue = "1") String clientId
	)

**Comment by federecio** [comment]
This seems to be an issue with the Swagger version being used.

**Comment by federecio** [comment]
Updating Swagger version seems to have fixed this issue. In case you want to try it use version 0.5.4-SNAPSHOT.

Since this one is an old issue will close it for now. Feel free to re-open it.
