### ISSUE TITLE
JSON Snake Case and model classes

### ISSUE THREAD

**Issue by carminexx** [federecio/dropwizard-swagger#29]
Hi,
I noticed that, even if I enabled JSON snake case serialization by dropwizard's @JsonSnakeCase annotation on top of every model class, Dropwizard-Swagger generate API Models with classic camelCase (so it just prints out the Java variable name for each JSON field).

Is there an option to force Swagger to generate snake_case field names instead of camelCase ones?

**Comment by federecio** [comment]
I tried the annotation you mention and it works fine. I don't see what Swagger has to do with the serialization of the response as this is done by Dropwizard. I'm happy to help if you share a sample project.

Since this is an old issue, I will close it for now. Feel free to re-open.

**Comment by stidiovip** [comment]
I have the same issue here. I am using Dropwizard 0.7 and swagger-jaxrs_2.10 1.3.8
