### ISSUE TITLE
Unable to serve static assets when using this

### ISSUE THREAD

**Issue by amitjindal** [federecio/dropwizard-swagger#32]
Hi, I am trying to use this package in a dropwizard application. However as soon as I use this the static assets stop working.
```
public void initialize(Bootstrap<AppConfiguration> bootstrap) {
        bootstrap.addBundle(new AssetsBundle("/assets/app/", "/", "index.html"));
        bootstrap.addBundle(hibernateBundle);
        swaggerDropwizard.onInitialize(bootstrap);
    }
    public void run(AppConfiguration configuration,
                    Environment environment) throws Exception {
        this.configuration = configuration;
        environment.jersey().setUrlPattern("/api/*");
        environment.jersey().register(new ProjectResource(
            new ProjectDAO(hibernateBundle.getSessionFactory())));
        //initData.init();
        swaggerDropwizard.onRun(configuration, environment, "localhost");
}
```
Here, if I comment the last line: `swaggerDropwizard.onRun(configuration, environment, "localhost");`
the index.html starts working. However if I leave it, then I get a 404 on root path.
Is there a workaround for this?

**Comment by federecio** [comment]
Amit, this scenario hasn't been tested. The fact that you are adding your own AssetsBundle might conflict with the AssetsBundle that's used to serve Swagger assets. 

I will look into it.

**Comment by federecio** [comment]
This was certainly an issue. I pushed a new snapshot with a fix for it. Could you please try it out again and let me know if it works now?

The new version is 0.5.4-SNAPSHOT

Thanks.

**Comment by ipedrazas** [comment]
Federico, did you push 0.5.4?

I cannot find it in mavencentral.

**Comment by federecio** [comment]
The latest release supporting Dropwizard 0.7.x is 0.5.3

Active development is now being done supporting Dropwizard 0.8.x starting with version 0.6
