### ISSUE TITLE
No Content Returned

### ISSUE THREAD

**Issue by cluttered-code** [federecio/dropwizard-swagger#36]
Every call returns "No Content".  I make the actual rest calls using a client and I get the info i expect but when I use the Swagger I never get anything back.

**Comment by cluttered-code** [comment]
I am seeing the swagger gui sending the command to dropwizard and dropwizard is responding with a 200 but I get nothing in the gui

**Comment by cluttered-code** [comment]
This appears to only be an issue when I use the Swagger bundle.  using the regular SwaggerDropwizard works fine.

**Comment by ronso-rage** [comment]
@cluttered-code hey, i'm noticing the same issue, so can you elaborate on what you mean by using the regular SwaggerDropwizard?

**Comment by GreyRockSoftware** [comment]
I don't remember, this was closed almost a year ago.
