### ISSUE TITLE
Can you publish version 0.6 to maven repository?

### ISSUE THREAD

**Issue by eladidan** [federecio/dropwizard-swagger#45]
I've been holding off on upgrading to DW 0.8 for a while for this. 
Thanks (P.S. thanks for your time and effort in putting this bundle together. It's awesome)

**Comment by federecio** [comment]
I deployed it yesterday, see http://search.maven.org/#artifactdetails%7Cio.federecio%7Cdropwizard-swagger%7C0.6%7Cjar

Please let me know if there are any issues

**Comment by federecio** [comment]
Will close this for now, if there are any issues with the JAR itself feel free to re-open it or create another issue.
