### ISSUE TITLE
SwaggerResource path configuration

### ISSUE THREAD

**Issue by yen0x** [federecio/dropwizard-swagger#73]
We would like to be able to configure the default /swagger path. Is there a way to currently do it that we'd have missed?

**Comment by dvalfrid** [comment]
Did you find any solution?

**Comment by yen0x** [comment]
Not really. We just made an alias resource to redirect the path we wanted to use to swagger:

```
@GET
@Path("/doc")
public Response toSwagger() throws URISyntaxException {
    return Response.seeOther(new URI("/swagger")).build();
}
```
