### ISSUE TITLE
Allow to define custom swagger path

### ISSUE THREAD

**Issue by alexcom** [federecio/dropwizard-swagger#97]
The issue I encountered is that I have to have my APIs under `/api` path and swagger to reside under `/swagger`. To accomplish first part i specify `rootPath: /api` in `application.yml`.  For some reason **dropwizard-swagger** registers it's resources under `rootPath` which makes me access swagger under `/api/swagger`. I think this should be configurable. We should be able to fire swagger under the path we want to, not just where  other JAX-RS resources reside.

**Comment by jplock** [comment]
This project is abandoned. Please see my fork at https://github.com/smoketurner/dropwizard-swagger

**Comment by alexcom** [comment]
@jplock OK.  Does your fork address this kind of issue?

**Comment by jplock** [comment]
Maybe, I'm just saying this fork is no longer maintained and the one I maintain has had a lot of pull requests against it which may fix your issue.

**Comment by alexcom** [comment]
Well, in fact I use your fork, just came here from google by project's
name. I'll close this issue then.

Best regards,

Aleksandr Kravets

2017-02-03 14:44 GMT+02:00 Justin Plock <notifications@github.com>:
